apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-redis
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter-redis
  template:
    metadata:
      labels:
        app: exporter-redis
    spec:
      containers:
        - name: exporter-redis
          image: oliver006/redis_exporter
          ports:
            - containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: "redis.backend-services.svc.cluster.local:6379"

---
apiVersion: v1
kind: Service
metadata:
  name: exporter-redis
  namespace: monitoring
spec:
  ports:
    - port: 9121
      targetPort: 9121
  selector:
    app: exporter-redis