apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-rabbitmq
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter-rabbitmq
  template:
    metadata:
      labels:
        app: exporter-rabbitmq
    spec:
      containers:
        - name: exporter-rabbitmq
          image: kbudde/rabbitmq-exporter
          ports:
            - containerPort: 9419
          env:
            - name: RABBITMQ_URL
              value: "rabbitmq-service.backend-services.svc.cluster.local:5672"

---
apiVersion: v1
kind: Service
metadata:
  name: exporter-rabbitmq
  namespace: monitoring
spec:
  ports:
    - port: 9419
      targetPort: 9419
  selector:
    app: exporter-rabbitmq