apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-redis
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-redis
  template:
    metadata:
      labels:
        app: celery-worker-redis
    spec:
      containers:
        - name: celery-worker-redis
          image: kuber_macroeconomics_simulator:latest
          imagePullPolicy: Never
          command: ["sh", "-c", "sleep 25 && celery -A macroeconomics_simulator worker -l info --queues=redis_queue"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "macroeconomics_simulator.settings.kuberized"
            - name: CELERY_BROKER_URL
              value: "redis://redis.backend-services.svc.cluster.local:6379/1"
          volumeMounts:
            - mountPath: /app/media
              name: django-mediafiles-storage
      volumes:
        - name: django-mediafiles-storage
          persistentVolumeClaim:
            claimName: django-mediafiles-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: celery-worker-redis
  namespace: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: celery-worker-redis