version: '3.8'

services:
  redis:
    image: redis
    container_name: redis # most likely WON'T BE a message broker and will remain only for caching
    ports:
      - "6379:6379"
    networks:
      - localnet

  django-rest:
    build:
      context: ./macroeconomics_simulator
    container_name: django-rest
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    networks:
      - localnet

  react:
    build: ./frontend
    container_name: react
    ports:
      - "3000:3000"
    command: >
      sh -c "npm start"
    restart: unless-stopped
    networks:
      - internet
      - localnet

volumes:
  static_volume:

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
