version: '3.8'

services:
  redis: # later add RabbitMq for more serious tasks
    image: redis
    container_name: redis # most likely remain only for caching
    ports:
      - "6379:6379"
    networks:
      - localnet

  django-rest:
    build:
      context: ./macroeconomics_simulator
    container_name: django-rest_mes
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=macroeconomics_simulator.settings.dockerized
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 --settings=macroeconomics_simulator.settings.dockerized"
    restart: unless-stopped
    networks:
      - localnet

  react:
    build: ./frontend
    container_name: react_mes
    ports:
      - "3000:3000"
    environment: # instead of 192.168.1.25:80 write your local IPV4 address or remove environment from this container
      - REACT_APP_BASE_URL=http://192.168.1.25:80/api/v1
      - REACT_APP_WEBSOCKET_URL=ws://192.168.1.25:80/ws
    command: >
      sh -c "npm start"
    restart: unless-stopped
    networks:
      - localnet

  celery-worker-redis:
    build:
      context: ./macroeconomics_simulator
    container_name: celery-worker-redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - DJANGO_SETTINGS_MODULE=macroeconomics_simulator.settings.dockerized
    depends_on:
      - redis
    command: >
      sh -c "celery -A macroeconomics_simulator worker -l info"
    networks:
      - localnet

  celery-beat:
    build:
      context: ./macroeconomics_simulator
    container_name: celery_beat
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - DJANGO_SETTINGS_MODULE=macroeconomics_simulator.settings.dockerized
    depends_on:
      - redis
    command: >
      sh -c "celery -A macroeconomics_simulator beat -l INFO"
    networks:
      - localnet

  nginx:
    image: nginx
    container_name: nginx_mes
    depends_on:
      - django-rest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: >
      /bin/sh -c "
      if [ ! -f /etc/nginx/ssl/nginx.key ]; then
        mkdir -p /etc/nginx/ssl && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj '/CN=localhost';
      fi &&
      nginx -g 'daemon off;'"
    networks:
      - internet
      - localnet

volumes:
  static_volume:

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
