apiVersion: v1
kind: Namespace
metadata:
  name: backend-services
# the most important: PostgreSql, Redis, RabbitMq
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
# Django, Redis and RabbitMq workers
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
# Nginx and React(in prod version, so mainly Nginx)
---
apiVersion: v1
kind: Namespace
metadata:
  name: celery-beat
# celery-beat
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
# Prometheus, Grafana, and all related services for getting information