apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-mediafiles-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/media"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-mediafiles-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
