apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: kuber_frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          command: ["sh", "-c", "npm start"]
          env:
            - name: PORT
              value: "3001"
            - name: REACT_APP_BASE_URL
              value: "http://localhost:80/api/v1" # http://nginx.frontend.svc.cluster.local/api/v1
            - name: REACT_APP_BASE_SSE_URL
              value: "http://localhost:80/api/sse" # http://nginx.frontend.svc.cluster.local/api/sse
            - name: REACT_APP_WEBSOCKET_URL
              value: "ws://localhost:80/ws" # ws://nginx.frontend.svc.cluster.local/ws

---
apiVersion: v1
kind: Service
metadata:
  name: react
  namespace: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: react